dist: xenial

matrix:
  include:
    - env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.1
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0
    - env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.5
    - env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=5.8.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^8.0

before_install:
  - travis_retry docker pull registry.gitlab.com/grahamcampbell/php:$PHP_VERSION
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "symfony/lts:${SYMFONY_VERSION}" --no-update -n
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n

install:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION install --no-suggest --prefer-dist -n -o

script:
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:$PHP_VERSION --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint ocular registry.gitlab.com/grahamcampbell/php:$PHP_VERSION code-coverage:upload --format=php-clover build/logs/clover.xml
