language: php

sudo: false

matrix:
  include:
    - php: 5.5.9
      env: LARAVEL_VERSION=5.1.*
    - php: 5.5.9
      env: LARAVEL_VERSION=5.2.*
    - php: 5.5
      env: LARAVEL_VERSION=5.1.*
    - php: 5.5
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_VERSION=5.1.*
    - php: 5.6
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_VERSION=5.3.*
    - php: 5.6
      env: LARAVEL_VERSION=5.4.*
    - php: 7.0
      env: LARAVEL_VERSION=5.1.*
    - php: 7.0
      env: LARAVEL_VERSION=5.2.*
    - php: 7.0
      env: LARAVEL_VERSION=5.3.*
    - php: 7.0
      env: LARAVEL_VERSION=5.4.*
    - php: 7.1
      env: LARAVEL_VERSION=5.1.*
    - php: 7.1
      env: LARAVEL_VERSION=5.2.*
    - php: 7.1
      env: LARAVEL_VERSION=5.3.*
    - php: 7.1
      env: LARAVEL_VERSION=5.4.*
    - php: hhvm
      env: LARAVEL_VERSION=5.1.*
    - php: hhvm
      env: LARAVEL_VERSION=5.2.*
    - php: hhvm
      env: LARAVEL_VERSION=5.3.*
    - php: hhvm
      env: LARAVEL_VERSION=5.4.*

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi
  - composer self-update --stable -n
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
