name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']
        laravel: ['6', '7', '8']
        exclude:
          - php: '7.2'
            laravel: '8'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Laravel 6
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:6.*" --no-update --no-interaction
        if: "matrix.laravel == '6'"

      - name: Select Laravel 7
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:7.*" --no-update --no-interaction
        if: "matrix.laravel == '7'"

      - name: Select Laravel 8
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:8.*" --no-update --no-interaction
        if: "matrix.laravel == '8'"

      - name: Install PHP 7 Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress
        if: "matrix.php < 8"

      - name: Install PHP 8 Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress --ignore-platform-req=php
        if: "matrix.php >= 8"

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
